### ISSUE TITLE
Software crashing when a soundfont path has been inserted (OmniMIDI.dll)

### ISSUE THREAD

**Issue by CoolCode124** [BlackMIDIDevs/xsynth#103]
So I was using PFA-Viz for this, when I put the .dll file into the folder where my software I use, it works without audio, so when i put the path of my chosen soundfont on soundfonts.json file and saved it, the software won't open, I tried an another soundfont in the different path directory, it keeps crashing. When I removed the file path, it opens again. I don't really know if it's my issue or the software I used or the synthesizer itself, here is a video.

**Comment by CoolCode124** [comment]
Uploading 2024-08-31 19-46-01.mp4…

**Comment by CoolCode124** [comment]
https://github.com/user-attachments/assets/9f6bcdf2-c6f6-4673-931f-5095db81a7fc

**Comment by Kaydax** [comment]
The path must be surrounded by quotes, try that

**Comment by arduano** [comment]
Also when surrounded by quotes, backslashes should be double backslashes `\\` or forward slashes `/` because of how JSON works
