### ISSUE TITLE
How can I run the MacOS version of this?

### ISSUE THREAD

**Issue by qingy1337** [BlackMIDIDevs/xsynth#104]
I'm not sure how to actually run it...

**Comment by Kaydax** [comment]
By using [wasabi](https://github.com/BlackMIDIDevs/wasabi) or by compiling xsynth yourself and running the examples

**Comment by qingy1337** [comment]
Hi @Kaydax, thanks for the quick response!
I tried running wasabi and I got this error message, is this supposed to happen?

```
thread 'main' panicked at src/renderer.rs:45:44:
called `Result::unwrap()` on an `Err` value: LibraryLoadFailure(DlOpen { desc: "dlopen(libvulkan.1.dylib, 0x0005): tried: \'libvulkan.1.dylib\' (no such file), \'/System/Volumes/Preboot/Cryptexes/OSlibvulkan.1.dylib\' (no such file), \'/usr/lib/libvulkan.1.dylib\' (no such file, not in dyld cache), \'libvulkan.1.dylib\' (no such file)" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kaydax** [comment]
> Hi @Kaydax, thanks for the quick response! I tried running wasabi and I got this error message, is this supposed to happen?
> 
> ```
> thread 'main' panicked at src/renderer.rs:45:44:
> called `Result::unwrap()` on an `Err` value: LibraryLoadFailure(DlOpen { desc: "dlopen(libvulkan.1.dylib, 0x0005): tried: \'libvulkan.1.dylib\' (no such file), \'/System/Volumes/Preboot/Cryptexes/OSlibvulkan.1.dylib\' (no such file), \'/usr/lib/libvulkan.1.dylib\' (no such file, not in dyld cache), \'libvulkan.1.dylib\' (no such file)" })
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Edit: I tried to install Vulkan and then after I ran the script I got this:
> 
> ```
> thread 'main' panicked at src/renderer.rs:61:10:
> Failed to create instance: IncompatibleDriver
> stack backtrace:
>    0:        0x10270764c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc0de1e130c6f75a8
>    1:        0x10253bceb - core::fmt::write::hd7454a2db9b355a4
>    2:        0x1026e0002 - std::io::Write::write_fmt::he0cba29e2e54b39e
>    3:        0x10270bd21 - std::sys_common::backtrace::print::hc728a8c02c27951e
>    4:        0x10270b4bc - std::panicking::default_hook::{{closure}}::h67d915f220aa191d
>    5:        0x10270d08f - std::panicking::rust_panic_with_hook::h206fe2aca02387c5
>    6:        0x10270c034 - std::panicking::begin_panic_handler::{{closure}}::hd764a9293c104dde
>    7:        0x10270bf89 - std::sys_common::backtrace::__rust_end_short_backtrace::h1e8bcfafbf8ab868
>    8:        0x10270bf76 - _rust_begin_unwind
>    9:        0x102918755 - core::panicking::panic_fmt::hbf6282ed69c8e1fb
>   10:        0x102918ba5 - core::result::unwrap_failed::hb8d7fcfb917aa825
>   11:        0x102499419 - wasabi::renderer::Renderer::new::h6d2f61772e09bdea
>   12:        0x1024af443 - wasabi::main::h044acfbb62430305
>   13:        0x10238ca36 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2c8b9c363e783233
>   14:        0x1024b9676 - _main
> ```

This is due to the fact wasabi uses vulkan. To fix this you must use MoltenVK

**Comment by qingy1337** [comment]
Ok I installed Vulkan + MoltenVK and then cloned the github repo for wasabi,
then I ran `cargo build` inside, and everything compiled successfully, so I did `cargo run` and I got this:




<img width="546" alt="image" src="https://github.com/user-attachments/assets/f6e0cff9-0d32-4307-8730-afaee0ebfc13">
