### ISSUE TITLE
Render arbitrarily stops rendering but keeps writing to file, resulting in long but empty output files

### ISSUE THREAD

**Issue by Lucas9810** [BlackMIDIDevs/xsynth#32]
Steps to reproduce: Compile render cargo (My compiled executable: [render.zip](https://github.com/arduano/xsynth/files/10365521/render.zip))
Attempt to render a midi such as CPU Fryer 2 ([CPU Fryer 2 Final.zip](https://github.com/arduano/xsynth/files/10365518/CPU.Fryer.2.Final.zip)) or [Po Pi Po V4](https://drive.google.com/file/d/1CZ8Bhnrxv7wFXMaoBvDBzD9-74RwgWco/view?usp=share_link) 
Resulting file will render approximately 0.1 seconds of the MIDI and the rest of the file will be blank ([bruh.zip](https://github.com/arduano/xsynth/files/10365519/bruh.zip), Resulting audio for CPU Fryer) ([bruh2.zip](https://github.com/arduano/xsynth/files/10365529/bruh2.zip), resulting audio for Po Pi Po)
Tested on several larger MIDIs (Shown is 70GB MIDI), resulting in error messages relating to midi-toolkit
![cmd_3yXbgryiDY](https://user-images.githubusercontent.com/48129427/211131514-9724b673-3100-4e33-a9c4-4d8a9fe4f995.png)
So, renderer seems to give up between 680 million notes (Successful test with Bad Apple Betelgeuse mode) and 2.4 Billion notes (Failed on Po Pi Po V4), but gives the midi-toolkit error on extremely high notecounts (between 2.4 billion and 9 billion)

**Comment by arduano** [comment]
Ok nvm, CPU fryer is corrupt because it has an invalid system exclusive message event on track 26, gonna check the others later

**Comment by Lucas9810** [comment]
Also, it seems like xsynth seems to not end the render properly on any midi and gets stuck in some form of loop, causing 100% cpu usage even though the output file has been fully and successfully written to
![explorer_3Ctwtal8Wo](https://user-images.githubusercontent.com/48129427/211164766-7916eedc-5347-4b2f-81fe-01681eaecbd3.png)

**Comment by Lucas9810** [comment]
> I'm not sure if safc is able to fix that kind of corruption too.

Still has the same issue after putting it through SAFC so I am assuming not; I will let alex know

**Comment by MyBlackMIDIScore** [comment]
Closing this because it was probably fixed in later versions of MTK. If not, open a new issue there. The render stuff was fixed a while back.
