### ISSUE TITLE
Crackling/popping under pipewire-pulse

### ISSUE THREAD

**Issue by SolsticeSpectrum** [BlackMIDIDevs/xsynth#71]
I don't know why but when playing midis in wasabi under pipewire, there's a lot of crackling.
I only recently switched from pulseaudio to pipewire, this issue wasn't present in pulseaudio and only got introduced with swtiching to pipewire-pulse.

I want to keep pipewire because of Discord audio streaming capabilities.

**Comment by DarkReaper231** [comment]
Enabling "Fade out voice when killing it" fixes it

**Comment by kohakow** [comment]
Quite late but I'm sure this is problem with ALSA + Pipewire, XSynth does not output audio to Pipewire nor Pulseaudio, it just outputs it to bare ALSA and then gets re-binded (or something else) to Pipewire.

I had the same issue with default Pipewire config, I had to change it to reduce audio latency in certain rhythm games, I also did other stuff to it and somehow got fixed

Unfortunately I had an issue where driver from AUR broke my whole kernel and debugging resulted in configs being reset, so I cannot provide mine here

**Comment by arduano** [comment]
I'll assume this issue is with an upstream package (e.g. alsa/pipewire) and not inherently xsynth's fault. xsynth outputs via "cpal" which I believe goes straight to alsa.

Feel free to re-open if this is actually an issue with xsynth
